Adding mssql as a test db
metabase/metabase-qa pull request #33
Opened 2023-03-03 17:50 UTC by paoliniluis

2023-03-03 20:34 UTC, metamben requested changes
- There are some copy&paste errors. 
- I hope we can get an arm64 image too.
- I couldn't build the image -- I was getting a login error:
  > 2023-03-03 20:31:39.55 Logon       Login failed for user 'sa'. Reason: An error occurred while evaluating the password. [CLIENT: 127.0.0.1]

2023-03-04 22:33 UTC, paoliniluis commented on .github/workflows/build-and-push.yml
> +        version: [2017, 2019, 2022]
they have a latest tag which is 2019, we can have a latest tag as well but as it seems that the Dockerfile changes on every latest tag the build will fail eventually

2023-03-04 22:34 UTC, paoliniluis commented
I think they only ship amd64 arch for this stuff https://hub.docker.com/_/microsoft-mssql-server

2023-03-05 10:41 UTC, metamben commented
> I think they only ship amd64 arch for this stuff https://hub.docker.com/_/microsoft-mssql-server

Can you check this again? Unless I'm confusing things, I could find an arm64 image.

2023-03-05 10:44 UTC, metamben commented on .github/workflows/build-and-push.yml
> +        version: [2017, 2019, 2022]
Is there no 2022 version?

2023-03-05 14:09 UTC, paoliniluis commented
just did a re-check, only amd64, no aarch64 or armv8 stuff

2023-03-06 15:15 UTC, metamben approved these changes

2023-03-06 15:32 UTC, merged